/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class Vibrato2pluginAudioProcessorEditor  : public AudioProcessorEditor, public SliderListener, public ButtonListener
{
public:
    Vibrato2pluginAudioProcessorEditor (Vibrato2pluginAudioProcessor& p);
    ~Vibrato2pluginAudioProcessorEditor();
//    void 
    
    //for slider
    void sliderValueChanged(Slider *slider);
    
    //for button
    void buttonClicked(Button* buttonIsClicked) override;
    
    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    class ParameterSlider;
    
    ScopedPointer<ParameterSlider> amplitudeSlider, frequencySlider;
    Label  amplitudeLabel, frequencyLabel;
    
    // Bypass button
    ToggleButton bypassButton;
    bool bypassButtonState;


    Vibrato2pluginAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (Vibrato2pluginAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
